const SQL = require('./utils/sql-string');

exports.transactions = SQL`
  id VARCHAR ENCODE lzo NULL,
  status VARCHAR ENCODE lzo NULL,
  type VARCHAR ENCODE lzo NULL,
  currency_iso_code VARCHAR ENCODE lzo NULL,
  amount DECIMAL(10,2) ENCODE RAW NULL,
  merchant_account_id VARCHAR ENCODE lzo NULL,
  sub_merchant_account_id VARCHAR ENCODE lzo NULL,
  master_merchant_account_id VARCHAR ENCODE lzo NULL,
  order_id VARCHAR ENCODE lzo NULL,
  refund_id VARCHAR ENCODE lzo NULL,
  refunded_transaction_id VARCHAR ENCODE lzo NULL,
  authorized_transaction_id VARCHAR ENCODE lzo NULL,
  settlement_batch_id VARCHAR ENCODE lzo NULL,
  custom_fields VARCHAR ENCODE lzo NULL,
  avs_error_response_code CHAR ENCODE lzo NULL,
  avs_postal_code_response_code CHAR ENCODE lzo NULL,
  avs_street_address_response_code CHAR ENCODE lzo NULL,
  cvv_response_code CHAR ENCODE lzo NULL,
  gateway_rejection_reason VARCHAR ENCODE lzo NULL,
  processor_authorization_code VARCHAR ENCODE lzo NULL,
  processor_response_code VARCHAR ENCODE lzo NULL,
  processor_response_text VARCHAR ENCODE lzo NULL,
  additional_processor_response VARCHAR ENCODE lzo NULL,
  voice_referral_number VARCHAR ENCODE lzo NULL,
  purchase_order_number VARCHAR ENCODE lzo NULL,
  tax_amount DECIMAL(10,2) ENCODE RAW NULL,
  tax_exempt BOOLEAN ENCODE RAW NULL,
  plan_id VARCHAR ENCODE lzo NULL,
  subscription_id VARCHAR ENCODE lzo NULL,
  recurring BOOLEAN ENCODE RAW NULL,
  channel VARCHAR ENCODE lzo NULL,
  service_fee_amount DECIMAL(10,2) ENCODE RAW NULL,
  escrow_status VARCHAR ENCODE lzo NULL,
  payment_instrument_type VARCHAR ENCODE lzo NULL,
  processor_settlement_response_code VARCHAR ENCODE lzo NULL,
  processor_settlement_response_text VARCHAR ENCODE lzo NULL,
  three_d_secure_info VARCHAR ENCODE lzo NULL,
  ships_from_postal_code VARCHAR ENCODE lzo NULL,
  shipping_amount DECIMAL(10,2) ENCODE RAW NULL,
  discount_amount DECIMAL(10,2) ENCODE RAW NULL,
  customer_id VARCHAR ENCODE lzo NULL,
  customer_first_name VARCHAR ENCODE lzo NULL,
  customer_last_name VARCHAR ENCODE lzo NULL,
  customer_company VARCHAR ENCODE lzo NULL,
  customer_email VARCHAR ENCODE lzo NULL,
  customer_website VARCHAR ENCODE lzo NULL,
  customer_phone VARCHAR ENCODE lzo NULL,
  customer_fax VARCHAR ENCODE lzo NULL,
  billing_id VARCHAR ENCODE lzo NULL,
  billing_first_name VARCHAR ENCODE lzo NULL,
  billing_last_name VARCHAR ENCODE lzo NULL,
  billing_company VARCHAR ENCODE lzo NULL,
  billing_street_address VARCHAR ENCODE lzo NULL,
  billing_extended_address VARCHAR ENCODE lzo NULL,
  billing_locality VARCHAR ENCODE lzo NULL,
  billing_region VARCHAR ENCODE lzo NULL,
  billing_postal_code VARCHAR ENCODE lzo NULL,
  billing_country_name VARCHAR ENCODE lzo NULL,
  billing_country_code_alpha2 VARCHAR ENCODE lzo NULL,
  billing_country_code_alpha3 VARCHAR ENCODE lzo NULL,
  billing_country_code_numeric VARCHAR ENCODE lzo NULL,
  shipping_id VARCHAR ENCODE lzo NULL,
  shipping_first_name VARCHAR ENCODE lzo NULL,
  shipping_last_name VARCHAR ENCODE lzo NULL,
  shipping_company VARCHAR ENCODE lzo NULL,
  shipping_street_address VARCHAR ENCODE lzo NULL,
  shipping_extended_address VARCHAR ENCODE lzo NULL,
  shipping_locality VARCHAR ENCODE lzo NULL,
  shipping_region VARCHAR ENCODE lzo NULL,
  shipping_postal_code VARCHAR ENCODE lzo NULL,
  shipping_country_name VARCHAR ENCODE lzo NULL,
  shipping_country_code_alpha2 VARCHAR ENCODE lzo NULL,
  shipping_country_code_alpha3 VARCHAR ENCODE lzo NULL,
  shipping_country_code_numeric VARCHAR ENCODE lzo NULL,
  credit_card_token VARCHAR ENCODE lzo NULL,
  credit_card_bin VARCHAR ENCODE lzo NULL,
  credit_card_last_4 VARCHAR ENCODE lzo NULL,
  credit_card_card_type VARCHAR ENCODE lzo NULL,
  credit_card_expiration_month VARCHAR ENCODE lzo NULL,
  credit_card_expiration_year VARCHAR ENCODE lzo NULL,
  credit_card_customer_location VARCHAR ENCODE lzo NULL,
  credit_card_cardholder_name VARCHAR ENCODE lzo NULL,
  credit_card_image_url VARCHAR ENCODE lzo NULL,
  credit_card_prepaid VARCHAR ENCODE lzo NULL,
  credit_card_healthcare VARCHAR ENCODE lzo NULL,
  credit_card_debit VARCHAR ENCODE lzo NULL,
  credit_card_durbin_regulated VARCHAR ENCODE lzo NULL,
  credit_card_commercial VARCHAR ENCODE lzo NULL,
  credit_card_payroll VARCHAR ENCODE lzo NULL,
  credit_card_issuing_bank VARCHAR ENCODE lzo NULL,
  credit_card_country_of_issuance VARCHAR ENCODE lzo NULL,
  credit_card_product_id VARCHAR ENCODE lzo NULL,
  credit_card_unique_mumber_identifier VARCHAR ENCODE lzo NULL,
  credit_card_venmo_sdk VARCHAR ENCODE lzo NULL,
  credit_card_masked_number VARCHAR ENCODE lzo NULL,
  credit_card_expiration_date VARCHAR ENCODE lzo NULL,
  subscription_billing_period_end_date VARCHAR ENCODE lzo NULL,
  subscription_billing_period_start_date VARCHAR ENCODE lzo NULL,
  disbursement_date VARCHAR ENCODE lzo NULL,
  disbursement_funds_held VARCHAR ENCODE lzo NULL,
  disbursement_settlement_amount VARCHAR ENCODE lzo NULL,
  disbursement_settlement_currency_exchange_rate VARCHAR ENCODE lzo NULL,
  disbursement_settlement_currency_iso_code VARCHAR ENCODE lzo NULL,
  disbursement_success VARCHAR ENCODE lzo NULL,
  descriptor_name VARCHAR ENCODE lzo NULL,
  descriptor_phone VARCHAR ENCODE lzo NULL,
  descriptor_url VARCHAR ENCODE lzo NULL,
  created_at TIMESTAMP ENCODE lzo NULL,
  updated_at TIMESTAMP ENCODE lzo NULL
`;

/* extra transaction columns
  -- refund_ids VARCHAR,
  -- partial_settlement_transaction_ids VARCHAR,
  -- add_ons VARCHAR,
  -- discounts VARCHAR,
  -- disputes VARCHAR,
  -- authorization_adjustments VARCHAR,
  -- paypal_account VARCHAR,
  -- coinbase_ccount VARCHAR,
  -- apple_pay_card VARCHAR(MAX),
  -- android_pay_card VARCHAR(MAX),
  -- visa_checkout_card VARCHAR(MAX),
  -- masterpass_card VARCHAR(MAX),
  -- status_history VARCHAR(MAX) */

exports.subscriptions = SQL`
  id VARCHAR ENCODE LZO,
  balance DECIMAL(10,2) ENCODE RAW,
  created_at TIMESTAMP ENCODE LZO,
  updated_at TIMESTAMP ENCODE LZO,
  billing_period_start_date TIMESTAMP ENCODE LZO,
  billing_period_end_date TIMESTAMP ENCODE LZO,
  billing_day_of_month INTEGER ENCODE LZO,
  current_billing_cycle INTEGER ENCODE LZO,
  days_past_due INTEGER ENCODE LZO,
  failure_count INTEGER ENCODE LZO,
  description VARCHAR ENCODE LZO,
  first_billing_date TIMESTAMP ENCODE LZO,
  merchant_account_id VARCHAR ENCODE LZO,
  never_expires BOOLEAN ENCODE RAW,
  next_bill_amount DECIMAL(10,2) ENCODE RAW,
  next_billing_date TIMESTAMP ENCODE LZO,
  next_billing_period_amount DECIMAL(10,2) ENCODE RAW,
  number_of_billing_cycles INTEGER ENCODE LZO,
  paid_through_date TIMESTAMP ENCODE LZO,
  payment_method_token VARCHAR ENCODE LZO,
  plan_id VARCHAR ENCODE LZO,
  price DECIMAL(10,2) ENCODE RAW,
  status VARCHAR ENCODE LZO,
  trial_duration INTEGER ENCODE LZO,
  trial_duration_unit VARCHAR ENCODE LZO,
  trial_period BOOLEAN ENCODE RAW
`;

exports.disputes = SQL`
  id VARCHAR ENCODE LZO,
  amount_disputed DECIMAL(10,2) ENCODE RAW,
  amount_won DECIMAL(10,2) ENCODE RAW,
  case_number DECIMAL ENCODE LZO,
  created_at TIMESTAMP ENCODE LZO,
  updated_at TIMESTAMP ENCODE LZO,
  currency_iso_code VARCHAR ENCODE LZO,
  kind VARCHAR ENCODE LZO,
  merchant_account_id VARCHAR ENCODE LZO,
  original_dispute_id VARCHAR ENCODE LZO,
  processor_comments VARCHAR ENCODE LZO,
  reason VARCHAR ENCODE LZO,
  reason_code VARCHAR ENCODE LZO,
  reason_description VARCHAR ENCODE LZO,
  received_date TIMESTAMP ENCODE LZO,
  reference_number  VARCHAR ENCODE LZO,
  reply_by_date TIMESTAMP ENCODE LZO,
  status  VARCHAR ENCODE LZO,
  transaction_id VARCHAR ENCODE LZO
`;
